package com.nt.service_PHINE.RouterService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-04-17T09:26:29.607+08:00
 * Generated source version: 3.1.18
 *
 */
@WebService(targetNamespace = "http://Microsoft.ServiceModel.Samples", name = "IRouter")
@XmlSeeAlso({ObjectFactory.class})
public interface IRouter {

    @WebMethod(operationName = "GetDeviceServiceUrl", action = "http://Microsoft.ServiceModel.Samples/IRouter/GetDeviceServiceUrl")
    @Action(input = "http://Microsoft.ServiceModel.Samples/IRouter/GetDeviceServiceUrl", output = "http://Microsoft.ServiceModel.Samples/IRouter/GetDeviceServiceUrlResponse")
    @RequestWrapper(localName = "GetDeviceServiceUrl", targetNamespace = "http://Microsoft.ServiceModel.Samples", className = "GetDeviceServiceUrl")
    @ResponseWrapper(localName = "GetDeviceServiceUrlResponse", targetNamespace = "http://Microsoft.ServiceModel.Samples", className = "GetDeviceServiceUrlResponse")
    public void getDeviceServiceUrl(
            @WebParam(name = "deviceId", targetNamespace = "http://Microsoft.ServiceModel.Samples")
                    String deviceId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "serviceUrl", targetNamespace = "http://Microsoft.ServiceModel.Samples")
                    javax.xml.ws.Holder<String> serviceUrl,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetDeviceServiceUrlResult", targetNamespace = "http://Microsoft.ServiceModel.Samples")
                    javax.xml.ws.Holder<Boolean> getDeviceServiceUrlResult
    );

    @WebMethod(operationName = "Add", action = "http://Microsoft.ServiceModel.Samples/IRouter/Add")
    @Action(input = "http://Microsoft.ServiceModel.Samples/IRouter/Add", output = "http://Microsoft.ServiceModel.Samples/IRouter/AddResponse")
    @RequestWrapper(localName = "Add", targetNamespace = "http://Microsoft.ServiceModel.Samples", className = "Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://Microsoft.ServiceModel.Samples", className = "AddResponse")
    @WebResult(name = "AddResult", targetNamespace = "http://Microsoft.ServiceModel.Samples")
    public Double add(
            @WebParam(name = "n1", targetNamespace = "http://Microsoft.ServiceModel.Samples")
                    Double n1,
            @WebParam(name = "n2", targetNamespace = "http://Microsoft.ServiceModel.Samples")
                    Double n2
    );
}
