package com.nt.service_PHINE.RouterService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-04-17T09:26:29.614+08:00
 * Generated source version: 3.1.18
 *
 */
@WebServiceClient(name = "RouterService",
                  wsdlLocation = "http://58.241.22.107:8733/WcfServiceLib_VerityPlatform/RouterService?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class RouterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RouterService");
    public final static QName BasicHttpBindingIRouter = new QName("http://tempuri.org/", "BasicHttpBinding_IRouter");
    static {
        URL url = null;
        try {
            url = new URL("http://58.241.22.107:8733/WcfServiceLib_VerityPlatform/RouterService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RouterService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://58.241.22.107:8733/WcfServiceLib_VerityPlatform/RouterService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RouterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RouterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RouterService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RouterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RouterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RouterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IRouter
     */
    @WebEndpoint(name = "BasicHttpBinding_IRouter")
    public IRouter getBasicHttpBindingIRouter() {
        return super.getPort(BasicHttpBindingIRouter, IRouter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRouter
     */
    @WebEndpoint(name = "BasicHttpBinding_IRouter")
    public IRouter getBasicHttpBindingIRouter(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRouter, IRouter.class, features);
    }

}
