package com.nt.service_PHINE.DeviceCommunication;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-02-13T17:17:09.690+08:00
 * Generated source version: 3.1.18
 *
 */
@WebServiceClient(name = "HardwareDeviceService",
                  wsdlLocation = "http://localhost:8734/WcfServiceLib_HardwareDevice/HardwareDeviceService/?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class HardwareDeviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "HardwareDeviceService");
    public final static QName BasicHttpBindingIHardwareDeviceService = new QName("http://tempuri.org/", "BasicHttpBinding_IHardwareDeviceService");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8734/WcfServiceLib_HardwareDevice/HardwareDeviceService/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HardwareDeviceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8734/WcfServiceLib_HardwareDevice/HardwareDeviceService/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HardwareDeviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HardwareDeviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HardwareDeviceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HardwareDeviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HardwareDeviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HardwareDeviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IHardwareDeviceService
     */
    @WebEndpoint(name = "BasicHttpBinding_IHardwareDeviceService")
    public IHardwareDeviceService getBasicHttpBindingIHardwareDeviceService() {
        return super.getPort(BasicHttpBindingIHardwareDeviceService, IHardwareDeviceService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHardwareDeviceService
     */
    @WebEndpoint(name = "BasicHttpBinding_IHardwareDeviceService")
    public IHardwareDeviceService getBasicHttpBindingIHardwareDeviceService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIHardwareDeviceService, IHardwareDeviceService.class, features);
    }

}
