package com.nt.service_PHINE.DeviceCommunication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-02-27T13:50:37.918+08:00
 * Generated source version: 3.1.18
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IDeviceService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDeviceService {

    @WebMethod(operationName = "InterconnTestStart", action = "http://tempuri.org/IDeviceService/InterconnTestStart")
    @Action(input = "http://tempuri.org/IDeviceService/InterconnTestStart", output = "http://tempuri.org/IDeviceService/InterconnTestStartResponse")
    @RequestWrapper(localName = "InterconnTestStart", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnTestStart")
    @ResponseWrapper(localName = "InterconnTestStartResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnTestStartResponse")
    @WebResult(name = "InterconnTestStartResult", targetNamespace = "http://tempuri.org/")
    public Boolean interconnTestStart(
            @WebParam(name = "deviceSlotInfo", targetNamespace = "http://tempuri.org/")
                    ArrayOfDeviceSlotInfo deviceSlotInfo,
            @WebParam(name = "FilePath", targetNamespace = "http://tempuri.org/")
                    String filePath
    );

    @WebMethod(operationName = "SetFmcVoltageByFile", action = "http://tempuri.org/IDeviceService/SetFmcVoltageByFile")
    @Action(input = "http://tempuri.org/IDeviceService/SetFmcVoltageByFile", output = "http://tempuri.org/IDeviceService/SetFmcVoltageByFileResponse")
    @RequestWrapper(localName = "SetFmcVoltageByFile", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetFmcVoltageByFile")
    @ResponseWrapper(localName = "SetFmcVoltageByFileResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetFmcVoltageByFileResponse")
    @WebResult(name = "SetFmcVoltageByFileResult", targetNamespace = "http://tempuri.org/")
    public Boolean setFmcVoltageByFile(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(name = "fmcId", targetNamespace = "http://tempuri.org/")
                    Long fmcId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "GetFpgaConfigStatus", action = "http://tempuri.org/IDeviceService/GetFpgaConfigStatus")
    @Action(input = "http://tempuri.org/IDeviceService/GetFpgaConfigStatus", output = "http://tempuri.org/IDeviceService/GetFpgaConfigStatusResponse")
    @RequestWrapper(localName = "GetFpgaConfigStatus", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFpgaConfigStatus")
    @ResponseWrapper(localName = "GetFpgaConfigStatusResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFpgaConfigStatusResponse")
    public void getFpgaConfigStatus(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "configStatus", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ConfigStatus> configStatus,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetFpgaConfigStatusResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getFpgaConfigStatusResult
    );

    @WebMethod(operationName = "InterconnGetProcess", action = "http://tempuri.org/IDeviceService/InterconnGetProcess")
    @Action(input = "http://tempuri.org/IDeviceService/InterconnGetProcess", output = "http://tempuri.org/IDeviceService/InterconnGetProcessResponse")
    @RequestWrapper(localName = "InterconnGetProcess", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnGetProcess")
    @ResponseWrapper(localName = "InterconnGetProcessResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnGetProcessResponse")
    public void interconnGetProcess(
            @WebParam(mode = WebParam.Mode.INOUT, name = "CurrTestState", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<InterConnTestState> currTestState,
            @WebParam(mode = WebParam.Mode.OUT, name = "InterconnGetProcessResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> interconnGetProcessResult
    );

    @WebMethod(operationName = "StartConfigFpgaByFile", action = "http://tempuri.org/IDeviceService/StartConfigFpgaByFile")
    @Action(input = "http://tempuri.org/IDeviceService/StartConfigFpgaByFile", output = "http://tempuri.org/IDeviceService/StartConfigFpgaByFileResponse")
    @RequestWrapper(localName = "StartConfigFpgaByFile", targetNamespace = "http://tempuri.org/", className = "DeviceService.StartConfigFpgaByFile")
    @ResponseWrapper(localName = "StartConfigFpgaByFileResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.StartConfigFpgaByFileResponse")
    @WebResult(name = "StartConfigFpgaByFileResult", targetNamespace = "http://tempuri.org/")
    public Boolean startConfigFpgaByFile(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "RemoveDevice", action = "http://tempuri.org/IDeviceService/RemoveDevice")
    @Action(input = "http://tempuri.org/IDeviceService/RemoveDevice", output = "http://tempuri.org/IDeviceService/RemoveDeviceResponse")
    @RequestWrapper(localName = "RemoveDevice", targetNamespace = "http://tempuri.org/", className = "DeviceService.RemoveDevice")
    @ResponseWrapper(localName = "RemoveDeviceResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RemoveDeviceResponse")
    @WebResult(name = "RemoveDeviceResult", targetNamespace = "http://tempuri.org/")
    public Boolean removeDevice(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "OpenConnection", action = "http://tempuri.org/IDeviceService/OpenConnection")
    @Action(input = "http://tempuri.org/IDeviceService/OpenConnection", output = "http://tempuri.org/IDeviceService/OpenConnectionResponse")
    @RequestWrapper(localName = "OpenConnection", targetNamespace = "http://tempuri.org/", className = "DeviceService.OpenConnection")
    @ResponseWrapper(localName = "OpenConnectionResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.OpenConnectionResponse")
    @WebResult(name = "OpenConnectionResult", targetNamespace = "http://tempuri.org/")
    public ConnectionResult openConnection(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "GetFmcVoltage", action = "http://tempuri.org/IDeviceService/GetFmcVoltage")
    @Action(input = "http://tempuri.org/IDeviceService/GetFmcVoltage", output = "http://tempuri.org/IDeviceService/GetFmcVoltageResponse")
    @RequestWrapper(localName = "GetFmcVoltage", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFmcVoltage")
    @ResponseWrapper(localName = "GetFmcVoltageResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFmcVoltageResponse")
    public void getFmcVoltage(
            @WebParam(mode = WebParam.Mode.INOUT, name = "fmcVoltageObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<FmcVoltageObject> fmcVoltageObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetFmcVoltageResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getFmcVoltageResult
    );

    @WebMethod(operationName = "GetPllClock", action = "http://tempuri.org/IDeviceService/GetPllClock")
    @Action(input = "http://tempuri.org/IDeviceService/GetPllClock", output = "http://tempuri.org/IDeviceService/GetPllClockResponse")
    @RequestWrapper(localName = "GetPllClock", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetPllClock")
    @ResponseWrapper(localName = "GetPllClockResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetPllClockResponse")
    public void getPllClock(
            @WebParam(mode = WebParam.Mode.INOUT, name = "pllClockObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<PllClockObject> pllClockObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetPllClockResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getPllClockResult
    );

    @WebMethod(operationName = "GetFpgaConfigProgress", action = "http://tempuri.org/IDeviceService/GetFpgaConfigProgress")
    @Action(input = "http://tempuri.org/IDeviceService/GetFpgaConfigProgress", output = "http://tempuri.org/IDeviceService/GetFpgaConfigProgressResponse")
    @RequestWrapper(localName = "GetFpgaConfigProgress", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFpgaConfigProgress")
    @ResponseWrapper(localName = "GetFpgaConfigProgressResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetFpgaConfigProgressResponse")
    public void getFpgaConfigProgress(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "progress", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Long> progress,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetFpgaConfigProgressResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getFpgaConfigProgressResult
    );

    @WebMethod(operationName = "RegRead", action = "http://tempuri.org/IDeviceService/RegRead")
    @Action(input = "http://tempuri.org/IDeviceService/RegRead", output = "http://tempuri.org/IDeviceService/RegReadResponse")
    @RequestWrapper(localName = "RegRead", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegRead")
    @ResponseWrapper(localName = "RegReadResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegReadResponse")
    public void regRead(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(name = "regAddr", targetNamespace = "http://tempuri.org/")
                    Long regAddr,
            @WebParam(mode = WebParam.Mode.INOUT, name = "regData", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Long> regData,
            @WebParam(mode = WebParam.Mode.OUT, name = "RegReadResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> regReadResult
    );

    @WebMethod(operationName = "ReConfigFpga", action = "http://tempuri.org/IDeviceService/ReConfigFpga")
    @Action(input = "http://tempuri.org/IDeviceService/ReConfigFpga", output = "http://tempuri.org/IDeviceService/ReConfigFpgaResponse")
    @RequestWrapper(localName = "ReConfigFpga", targetNamespace = "http://tempuri.org/", className = "DeviceService.ReConfigFpga")
    @ResponseWrapper(localName = "ReConfigFpgaResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.ReConfigFpgaResponse")
    @WebResult(name = "ReConfigFpgaResult", targetNamespace = "http://tempuri.org/")
    public Boolean reConfigFpga(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId
    );

    @WebMethod(operationName = "StartConfigFpga", action = "http://tempuri.org/IDeviceService/StartConfigFpga")
    @Action(input = "http://tempuri.org/IDeviceService/StartConfigFpga", output = "http://tempuri.org/IDeviceService/StartConfigFpgaResponse")
    @RequestWrapper(localName = "StartConfigFpga", targetNamespace = "http://tempuri.org/", className = "DeviceService.StartConfigFpga")
    @ResponseWrapper(localName = "StartConfigFpgaResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.StartConfigFpgaResponse")
    @WebResult(name = "StartConfigFpgaResult", targetNamespace = "http://tempuri.org/")
    public Boolean startConfigFpga(
            @WebParam(name = "fpgaConfigObject", targetNamespace = "http://tempuri.org/")
                    FpgaConfigObject fpgaConfigObject
    );

    @WebMethod(operationName = "SetFmcVoltage", action = "http://tempuri.org/IDeviceService/SetFmcVoltage")
    @Action(input = "http://tempuri.org/IDeviceService/SetFmcVoltage", output = "http://tempuri.org/IDeviceService/SetFmcVoltageResponse")
    @RequestWrapper(localName = "SetFmcVoltage", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetFmcVoltage")
    @ResponseWrapper(localName = "SetFmcVoltageResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetFmcVoltageResponse")
    @WebResult(name = "SetFmcVoltageResult", targetNamespace = "http://tempuri.org/")
    public Boolean setFmcVoltage(
            @WebParam(name = "fmcVoltageObject", targetNamespace = "http://tempuri.org/")
                    FmcVoltageObject fmcVoltageObject
    );

    @WebMethod(operationName = "AddBoard", action = "http://tempuri.org/IDeviceService/AddBoard")
    @Action(input = "http://tempuri.org/IDeviceService/AddBoard", output = "http://tempuri.org/IDeviceService/AddBoardResponse")
    @RequestWrapper(localName = "AddBoard", targetNamespace = "http://tempuri.org/", className = "DeviceService.AddBoard")
    @ResponseWrapper(localName = "AddBoardResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.AddBoardResponse")
    @WebResult(name = "AddBoardResult", targetNamespace = "http://tempuri.org/")
    public Boolean addBoard(
            @WebParam(name = "boardInfo", targetNamespace = "http://tempuri.org/")
                    BoardInfo boardInfo
    );

    @WebMethod(operationName = "OfflineDevice", action = "http://tempuri.org/IDeviceService/OfflineDevice")
    @Action(input = "http://tempuri.org/IDeviceService/OfflineDevice", output = "http://tempuri.org/IDeviceService/OfflineDeviceResponse")
    @RequestWrapper(localName = "OfflineDevice", targetNamespace = "http://tempuri.org/", className = "DeviceService.OfflineDevice")
    @ResponseWrapper(localName = "OfflineDeviceResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.OfflineDeviceResponse")
    @WebResult(name = "OfflineDeviceResult", targetNamespace = "http://tempuri.org/")
    public Boolean offlineDevice(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "RegWrite", action = "http://tempuri.org/IDeviceService/RegWrite")
    @Action(input = "http://tempuri.org/IDeviceService/RegWrite", output = "http://tempuri.org/IDeviceService/RegWriteResponse")
    @RequestWrapper(localName = "RegWrite", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegWrite")
    @ResponseWrapper(localName = "RegWriteResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegWriteResponse")
    @WebResult(name = "RegWriteResult", targetNamespace = "http://tempuri.org/")
    public Boolean regWrite(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(name = "regAddr", targetNamespace = "http://tempuri.org/")
                    Long regAddr,
            @WebParam(name = "regData", targetNamespace = "http://tempuri.org/")
                    Long regData
    );

    @WebMethod(operationName = "GetCurrentConnStatus", action = "http://tempuri.org/IDeviceService/GetCurrentConnStatus")
    @Action(input = "http://tempuri.org/IDeviceService/GetCurrentConnStatus", output = "http://tempuri.org/IDeviceService/GetCurrentConnStatusResponse")
    @RequestWrapper(localName = "GetCurrentConnStatus", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetCurrentConnStatus")
    @ResponseWrapper(localName = "GetCurrentConnStatusResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.GetCurrentConnStatusResponse")
    public void getCurrentConnStatus(
            @WebParam(mode = WebParam.Mode.INOUT, name = "deviceConnStates", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ArrayOfDeviceConnState> deviceConnStates,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetCurrentConnStatusResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getCurrentConnStatusResult
    );

    @WebMethod(operationName = "SelfTest", action = "http://tempuri.org/IDeviceService/SelfTest")
    @Action(input = "http://tempuri.org/IDeviceService/SelfTest", output = "http://tempuri.org/IDeviceService/SelfTestResponse")
    @RequestWrapper(localName = "SelfTest", targetNamespace = "http://tempuri.org/", className = "DeviceService.SelfTest")
    @ResponseWrapper(localName = "SelfTestResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.SelfTestResponse")
    @WebResult(name = "SelfTestResult", targetNamespace = "http://tempuri.org/")
    public Boolean selfTest(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    ArrayOfstring deviceId,
            @WebParam(name = "filepath", targetNamespace = "http://tempuri.org/")
                    String filepath
    );

    @WebMethod(operationName = "RegBatRead", action = "http://tempuri.org/IDeviceService/RegBatRead")
    @Action(input = "http://tempuri.org/IDeviceService/RegBatRead", output = "http://tempuri.org/IDeviceService/RegBatReadResponse")
    @RequestWrapper(localName = "RegBatRead", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegBatRead")
    @ResponseWrapper(localName = "RegBatReadResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegBatReadResponse")
    public void regBatRead(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "boardIndex", targetNamespace = "http://tempuri.org/")
                    Integer boardIndex,
            @WebParam(mode = WebParam.Mode.INOUT, name = "fpgaBatchAccessObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ObjectFpgaBatchAccess> fpgaBatchAccessObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "RegBatReadResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> regBatReadResult
    );

    @WebMethod(operationName = "CloseConnection", action = "http://tempuri.org/IDeviceService/CloseConnection")
    @Action(input = "http://tempuri.org/IDeviceService/CloseConnection", output = "http://tempuri.org/IDeviceService/CloseConnectionResponse")
    @RequestWrapper(localName = "CloseConnection", targetNamespace = "http://tempuri.org/", className = "DeviceService.CloseConnection")
    @ResponseWrapper(localName = "CloseConnectionResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.CloseConnectionResponse")
    @WebResult(name = "CloseConnectionResult", targetNamespace = "http://tempuri.org/")
    public Boolean closeConnection(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "SetPllClockByFile", action = "http://tempuri.org/IDeviceService/SetPllClockByFile")
    @Action(input = "http://tempuri.org/IDeviceService/SetPllClockByFile", output = "http://tempuri.org/IDeviceService/SetPllClockByFileResponse")
    @RequestWrapper(localName = "SetPllClockByFile", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetPllClockByFile")
    @ResponseWrapper(localName = "SetPllClockByFileResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetPllClockByFileResponse")
    @WebResult(name = "SetPllClockByFileResult", targetNamespace = "http://tempuri.org/")
    public Boolean setPllClockByFile(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Long fpgaId,
            @WebParam(name = "pllId", targetNamespace = "http://tempuri.org/")
                    Long pllId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "OnlineDevice", action = "http://tempuri.org/IDeviceService/OnlineDevice")
    @Action(input = "http://tempuri.org/IDeviceService/OnlineDevice", output = "http://tempuri.org/IDeviceService/OnlineDeviceResponse")
    @RequestWrapper(localName = "OnlineDevice", targetNamespace = "http://tempuri.org/", className = "DeviceService.OnlineDevice")
    @ResponseWrapper(localName = "OnlineDeviceResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.OnlineDeviceResponse")
    @WebResult(name = "OnlineDeviceResult", targetNamespace = "http://tempuri.org/")
    public Boolean onlineDevice(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "AddDevice", action = "http://tempuri.org/IDeviceService/AddDevice")
    @Action(input = "http://tempuri.org/IDeviceService/AddDevice", output = "http://tempuri.org/IDeviceService/AddDeviceResponse")
    @RequestWrapper(localName = "AddDevice", targetNamespace = "http://tempuri.org/", className = "DeviceService.AddDevice")
    @ResponseWrapper(localName = "AddDeviceResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.AddDeviceResponse")
    @WebResult(name = "AddDeviceResult", targetNamespace = "http://tempuri.org/")
    public Boolean addDevice(
            @WebParam(name = "deviceInfo", targetNamespace = "http://tempuri.org/")
                    DeviceInfo deviceInfo
    );

    @WebMethod(operationName = "RegBatWrite", action = "http://tempuri.org/IDeviceService/RegBatWrite")
    @Action(input = "http://tempuri.org/IDeviceService/RegBatWrite", output = "http://tempuri.org/IDeviceService/RegBatWriteResponse")
    @RequestWrapper(localName = "RegBatWrite", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegBatWrite")
    @ResponseWrapper(localName = "RegBatWriteResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RegBatWriteResponse")
    public void regBatWrite(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "boardIndex", targetNamespace = "http://tempuri.org/")
                    Integer boardIndex,
            @WebParam(mode = WebParam.Mode.INOUT, name = "fpgaBatchAccessObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ObjectFpgaBatchAccess> fpgaBatchAccessObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "RegBatWriteResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> regBatWriteResult
    );

    @WebMethod(operationName = "InterconnGetResult", action = "http://tempuri.org/IDeviceService/InterconnGetResult")
    @Action(input = "http://tempuri.org/IDeviceService/InterconnGetResult", output = "http://tempuri.org/IDeviceService/InterconnGetResultResponse")
    @RequestWrapper(localName = "InterconnGetResult", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnGetResult")
    @ResponseWrapper(localName = "InterconnGetResultResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.InterconnGetResultResponse")
    public void interconnGetResult(
            @WebParam(mode = WebParam.Mode.INOUT, name = "InterConnStatus", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ArrayOfint> interConnStatus,
            @WebParam(mode = WebParam.Mode.INOUT, name = "ResultFilePath", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<String> resultFilePath,
            @WebParam(mode = WebParam.Mode.OUT, name = "InterconnGetResultResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> interconnGetResultResult
    );

    @WebMethod(operationName = "SetPllClock", action = "http://tempuri.org/IDeviceService/SetPllClock")
    @Action(input = "http://tempuri.org/IDeviceService/SetPllClock", output = "http://tempuri.org/IDeviceService/SetPllClockResponse")
    @RequestWrapper(localName = "SetPllClock", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetPllClock")
    @ResponseWrapper(localName = "SetPllClockResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.SetPllClockResponse")
    @WebResult(name = "SetPllClockResult", targetNamespace = "http://tempuri.org/")
    public Boolean setPllClock(
            @WebParam(name = "pllClockObject", targetNamespace = "http://tempuri.org/")
                    PllClockObject pllClockObject
    );

    @WebMethod(operationName = "OnlineDeviceAll", action = "http://tempuri.org/IDeviceService/OnlineDeviceAll")
    @Action(input = "http://tempuri.org/IDeviceService/OnlineDeviceAll", output = "http://tempuri.org/IDeviceService/OnlineDeviceAllResponse")
    @RequestWrapper(localName = "OnlineDeviceAll", targetNamespace = "http://tempuri.org/", className = "DeviceService.OnlineDeviceAll")
    @ResponseWrapper(localName = "OnlineDeviceAllResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.OnlineDeviceAllResponse")
    public void onlineDeviceAll(
            @WebParam(mode = WebParam.Mode.INOUT, name = "OnlineInfo", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<OnLineDeviceInfo> onlineInfo,
            @WebParam(mode = WebParam.Mode.OUT, name = "OnlineDeviceAllResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> onlineDeviceAllResult
    );

    @WebMethod(operationName = "RemoveBoard", action = "http://tempuri.org/IDeviceService/RemoveBoard")
    @Action(input = "http://tempuri.org/IDeviceService/RemoveBoard", output = "http://tempuri.org/IDeviceService/RemoveBoardResponse")
    @RequestWrapper(localName = "RemoveBoard", targetNamespace = "http://tempuri.org/", className = "DeviceService.RemoveBoard")
    @ResponseWrapper(localName = "RemoveBoardResponse", targetNamespace = "http://tempuri.org/", className = "DeviceService.RemoveBoardResponse")
    @WebResult(name = "RemoveBoardResult", targetNamespace = "http://tempuri.org/")
    public Boolean removeBoard(
            @WebParam(name = "boardId", targetNamespace = "http://tempuri.org/")
                    String boardId
    );
}
