
package com.nt.service_PHINE.DeviceCommunication;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-02-11T23:33:28.163+08:00
 * Generated source version: 3.1.18
 *
 */
public final class IHardwareDeviceService_BasicHttpBindingIHardwareDeviceService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "HardwareDeviceService");

    private IHardwareDeviceService_BasicHttpBindingIHardwareDeviceService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HardwareDeviceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HardwareDeviceService ss = new HardwareDeviceService(wsdlURL, SERVICE_NAME);
        IHardwareDeviceService port = ss.getBasicHttpBindingIHardwareDeviceService();
        {
	        System.out.println("Invoking closeConnection...");
	        String _closeConnection_deviceId = "device_1";
	        Boolean _closeConnection__return = port.closeConnection(_closeConnection_deviceId);
	        System.out.println("closeConnection.result=" + _closeConnection__return);
        }
//        {
//	        System.out.println("Invoking openConnection...");
//	        java.lang.String _openConnection_deviceId = "device_1";
//	        ConnectionResult _openConnection__return = port.openConnection(_openConnection_deviceId);
//	        System.out.println("openConnection.result=" + _openConnection__return);
//        }

        System.exit(0);
    }

}
