package com.nt.service_PHINE.DeviceCommunication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-02-13T17:17:09.681+08:00
 * Generated source version: 3.1.18
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IHardwareDeviceService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHardwareDeviceService {

    @WebMethod(operationName = "RegWrite", action = "http://tempuri.org/IHardwareDeviceService/RegWrite")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/RegWrite", output = "http://tempuri.org/IHardwareDeviceService/RegWriteResponse")
    @RequestWrapper(localName = "RegWrite", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.RegWrite")
    @ResponseWrapper(localName = "RegWriteResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.RegWriteResponse")
    @WebResult(name = "RegWriteResult", targetNamespace = "http://tempuri.org/")
    public Boolean regWrite(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Integer fpgaId,
            @WebParam(name = "regAddr", targetNamespace = "http://tempuri.org/")
                    Long regAddr,
            @WebParam(name = "regData", targetNamespace = "http://tempuri.org/")
                    Long regData
    );

    @WebMethod(operationName = "SetFmcVoltageByFile", action = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltageByFile")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltageByFile", output = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltageByFileResponse")
    @RequestWrapper(localName = "SetFmcVoltageByFile", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetFmcVoltageByFile")
    @ResponseWrapper(localName = "SetFmcVoltageByFileResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetFmcVoltageByFileResponse")
    @WebResult(name = "SetFmcVoltageByFileResult", targetNamespace = "http://tempuri.org/")
    public Boolean setFmcVoltageByFile(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "GetCurrentConnStatus", action = "http://tempuri.org/IHardwareDeviceService/GetCurrentConnStatus")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/GetCurrentConnStatus", output = "http://tempuri.org/IHardwareDeviceService/GetCurrentConnStatusResponse")
    @RequestWrapper(localName = "GetCurrentConnStatus", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetCurrentConnStatus")
    @ResponseWrapper(localName = "GetCurrentConnStatusResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetCurrentConnStatusResponse")
    public void getCurrentConnStatus(
            @WebParam(mode = WebParam.Mode.INOUT, name = "deviceConnStates", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<ArrayOfDeviceConnState> deviceConnStates,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetCurrentConnStatusResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getCurrentConnStatusResult
    );

    @WebMethod(operationName = "OpenConnection", action = "http://tempuri.org/IHardwareDeviceService/OpenConnection")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/OpenConnection", output = "http://tempuri.org/IHardwareDeviceService/OpenConnectionResponse")
    @RequestWrapper(localName = "OpenConnection", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.OpenConnection")
    @ResponseWrapper(localName = "OpenConnectionResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.OpenConnectionResponse")
    @WebResult(name = "OpenConnectionResult", targetNamespace = "http://tempuri.org/")
    public ConnectionResult openConnection(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "CloseConnection", action = "http://tempuri.org/IHardwareDeviceService/CloseConnection")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/CloseConnection", output = "http://tempuri.org/IHardwareDeviceService/CloseConnectionResponse")
    @RequestWrapper(localName = "CloseConnection", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.CloseConnection")
    @ResponseWrapper(localName = "CloseConnectionResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.CloseConnectionResponse")
    @WebResult(name = "CloseConnectionResult", targetNamespace = "http://tempuri.org/")
    public Boolean closeConnection(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId
    );

    @WebMethod(operationName = "ConfigFpga", action = "http://tempuri.org/IHardwareDeviceService/ConfigFpga")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/ConfigFpga", output = "http://tempuri.org/IHardwareDeviceService/ConfigFpgaResponse")
    @RequestWrapper(localName = "ConfigFpga", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.ConfigFpga")
    @ResponseWrapper(localName = "ConfigFpgaResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.ConfigFpgaResponse")
    @WebResult(name = "ConfigFpgaResult", targetNamespace = "http://tempuri.org/")
    public Boolean configFpga(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Integer fpgaId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "GetFmcVoltage", action = "http://tempuri.org/IHardwareDeviceService/GetFmcVoltage")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/GetFmcVoltage", output = "http://tempuri.org/IHardwareDeviceService/GetFmcVoltageResponse")
    @RequestWrapper(localName = "GetFmcVoltage", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetFmcVoltage")
    @ResponseWrapper(localName = "GetFmcVoltageResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetFmcVoltageResponse")
    public void getFmcVoltage(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "fmcVoltageObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<FmcVoltageObject> fmcVoltageObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetFmcVoltageResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getFmcVoltageResult
    );

    @WebMethod(operationName = "SetPllClockByFile", action = "http://tempuri.org/IHardwareDeviceService/SetPllClockByFile")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/SetPllClockByFile", output = "http://tempuri.org/IHardwareDeviceService/SetPllClockByFileResponse")
    @RequestWrapper(localName = "SetPllClockByFile", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetPllClockByFile")
    @ResponseWrapper(localName = "SetPllClockByFileResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetPllClockByFileResponse")
    @WebResult(name = "SetPllClockByFileResult", targetNamespace = "http://tempuri.org/")
    public Boolean setPllClockByFile(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "configFilePath", targetNamespace = "http://tempuri.org/")
                    String configFilePath
    );

    @WebMethod(operationName = "GetPllClock", action = "http://tempuri.org/IHardwareDeviceService/GetPllClock")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/GetPllClock", output = "http://tempuri.org/IHardwareDeviceService/GetPllClockResponse")
    @RequestWrapper(localName = "GetPllClock", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetPllClock")
    @ResponseWrapper(localName = "GetPllClockResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.GetPllClockResponse")
    public void getPllClock(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "pllClockObject", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<PllClockObject> pllClockObject,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetPllClockResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> getPllClockResult
    );

    @WebMethod(operationName = "RegRead", action = "http://tempuri.org/IHardwareDeviceService/RegRead")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/RegRead", output = "http://tempuri.org/IHardwareDeviceService/RegReadResponse")
    @RequestWrapper(localName = "RegRead", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.RegRead")
    @ResponseWrapper(localName = "RegReadResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.RegReadResponse")
    public void regRead(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Integer fpgaId,
            @WebParam(name = "regAddr", targetNamespace = "http://tempuri.org/")
                    Long regAddr,
            @WebParam(mode = WebParam.Mode.INOUT, name = "regData", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Long> regData,
            @WebParam(mode = WebParam.Mode.OUT, name = "RegReadResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Boolean> regReadResult
    );

    @WebMethod(operationName = "ReConfigFpga", action = "http://tempuri.org/IHardwareDeviceService/ReConfigFpga")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/ReConfigFpga", output = "http://tempuri.org/IHardwareDeviceService/ReConfigFpgaResponse")
    @RequestWrapper(localName = "ReConfigFpga", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.ReConfigFpga")
    @ResponseWrapper(localName = "ReConfigFpgaResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.ReConfigFpgaResponse")
    @WebResult(name = "ReConfigFpgaResult", targetNamespace = "http://tempuri.org/")
    public Boolean reConfigFpga(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fpgaId", targetNamespace = "http://tempuri.org/")
                    Integer fpgaId
    );

    @WebMethod(operationName = "SetPllClock", action = "http://tempuri.org/IHardwareDeviceService/SetPllClock")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/SetPllClock", output = "http://tempuri.org/IHardwareDeviceService/SetPllClockResponse")
    @RequestWrapper(localName = "SetPllClock", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetPllClock")
    @ResponseWrapper(localName = "SetPllClockResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetPllClockResponse")
    @WebResult(name = "SetPllClockResult", targetNamespace = "http://tempuri.org/")
    public Boolean setPllClock(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "pllClockObject", targetNamespace = "http://tempuri.org/")
                    PllClockObject pllClockObject
    );

    @WebMethod(operationName = "SetFmcVoltage", action = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltage")
    @Action(input = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltage", output = "http://tempuri.org/IHardwareDeviceService/SetFmcVoltageResponse")
    @RequestWrapper(localName = "SetFmcVoltage", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetFmcVoltage")
    @ResponseWrapper(localName = "SetFmcVoltageResponse", targetNamespace = "http://tempuri.org/", className = "HardwareDeviceService.SetFmcVoltageResponse")
    @WebResult(name = "SetFmcVoltageResult", targetNamespace = "http://tempuri.org/")
    public Boolean setFmcVoltage(
            @WebParam(name = "deviceId", targetNamespace = "http://tempuri.org/")
                    String deviceId,
            @WebParam(name = "fmcVoltageObject", targetNamespace = "http://tempuri.org/")
                    FmcVoltageObject fmcVoltageObject
    );
}
